/*
 * JSP generated by Resin Professional 4.0.53 (built Fri, 16 Jun 2017 02:25:02 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import tw.com.common.*;
import java.util.*;

public class _selecttrain__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
		String Id = request.getParameter("id");
		//\u9078\u53d6\u7684\u8eca\u5ec2
		String box = (String) request.getParameter("box");
		if (box == null || box.equals("null")) {
			box = "1";
		}
		TrainData trainDate = new TrainData();
		ArrayList<Station_trainItem> lists = trainDate.SelectTrainSeat(Id);
		if (lists != null) {
			Map<String, String> seat = lists.get(0).getSeat();
	
    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((lists.get(0).getId()));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    if (box.equals("1")) {
    out.write(_jsp_string3, 0, _jsp_string3.length);
    }
    out.write(_jsp_string4, 0, _jsp_string4.length);
    if (box.equals("2")) {
    out.write(_jsp_string3, 0, _jsp_string3.length);
    }
    out.write(_jsp_string5, 0, _jsp_string5.length);
    if (box.equals("3")) {
    out.write(_jsp_string3, 0, _jsp_string3.length);
    }
    out.write(_jsp_string6, 0, _jsp_string6.length);
    if (box.equals("4")) {
    out.write(_jsp_string3, 0, _jsp_string3.length);
    }
    out.write(_jsp_string7, 0, _jsp_string7.length);
    if (box.equals("5")) {
    out.write(_jsp_string3, 0, _jsp_string3.length);
    }
    out.write(_jsp_string8, 0, _jsp_string8.length);
    if (box.equals("6")) {
    out.write(_jsp_string3, 0, _jsp_string3.length);
    }
    out.write(_jsp_string9, 0, _jsp_string9.length);
    if (box.equals("7")) {
    out.write(_jsp_string3, 0, _jsp_string3.length);
    }
    out.write(_jsp_string10, 0, _jsp_string10.length);
    if (box.equals("8")) {
    out.write(_jsp_string3, 0, _jsp_string3.length);
    }
    out.write(_jsp_string11, 0, _jsp_string11.length);
    if (box.equals("9")) {
    out.write(_jsp_string3, 0, _jsp_string3.length);
    }
    out.write(_jsp_string12, 0, _jsp_string12.length);
    if (box.equals("10")) {
    out.write(_jsp_string3, 0, _jsp_string3.length);
    }
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print((seat.get("" + box + "A1")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "A1").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((seat.get("" + box + "A2")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "A2").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string17, 0, _jsp_string17.length);
    out.print((seat.get("" + box + "A3")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "A3").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print((seat.get("" + box + "A4")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "A4").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((seat.get("" + box + "A5")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "A5").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((seat.get("" + box + "A6")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "A6").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((seat.get("" + box + "A7")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "A7").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((seat.get("" + box + "A8")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "A8").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((seat.get("" + box + "A9")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "A9").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string24, 0, _jsp_string24.length);
    out.print((seat.get("" + box + "A10")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "A10").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string25, 0, _jsp_string25.length);
    out.print((seat.get("" + box + "B1")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "B1").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string26, 0, _jsp_string26.length);
    out.print((seat.get("" + box + "B2")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "B2").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string27, 0, _jsp_string27.length);
    out.print((seat.get("" + box + "B3")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "B3").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string28, 0, _jsp_string28.length);
    out.print((seat.get("" + box + "B4")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "B4").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string29, 0, _jsp_string29.length);
    out.print((seat.get("" + box + "B5")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "B5").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string30, 0, _jsp_string30.length);
    out.print((seat.get("" + box + "B6")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "B6").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string31, 0, _jsp_string31.length);
    out.print((seat.get("" + box + "B7")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "B7").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string32, 0, _jsp_string32.length);
    out.print((seat.get("" + box + "B8")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "B8").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string33, 0, _jsp_string33.length);
    out.print((seat.get("" + box + "B9")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "B9").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string34, 0, _jsp_string34.length);
    out.print((seat.get("" + box + "B10")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "B10").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string35, 0, _jsp_string35.length);
    out.print((seat.get("" + box + "C1")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "C1").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string36, 0, _jsp_string36.length);
    out.print((seat.get("" + box + "C2")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "C2").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string37, 0, _jsp_string37.length);
    out.print((seat.get("" + box + "C3")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "C3").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string38, 0, _jsp_string38.length);
    out.print((seat.get("" + box + "C4")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "C4").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string39, 0, _jsp_string39.length);
    out.print((seat.get("" + box + "C5")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "C5").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string40, 0, _jsp_string40.length);
    out.print((seat.get("" + box + "C6")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "C6").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string41, 0, _jsp_string41.length);
    out.print((seat.get("" + box + "C7")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "C7").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string42, 0, _jsp_string42.length);
    out.print((seat.get("" + box + "C8")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "C8").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string43, 0, _jsp_string43.length);
    out.print((seat.get("" + box + "C9")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "C9").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string44, 0, _jsp_string44.length);
    out.print((seat.get("" + box + "C10")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "C10").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string45, 0, _jsp_string45.length);
    out.print((seat.get("" + box + "D1")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "D1").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string46, 0, _jsp_string46.length);
    out.print((seat.get("" + box + "D2")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "D2").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string47, 0, _jsp_string47.length);
    out.print((seat.get("" + box + "D3")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "D3").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string48, 0, _jsp_string48.length);
    out.print((seat.get("" + box + "D4")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "D4").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string49, 0, _jsp_string49.length);
    out.print((seat.get("" + box + "D5")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "D5").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string50, 0, _jsp_string50.length);
    out.print((seat.get("" + box + "D6")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "D6").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string51, 0, _jsp_string51.length);
    out.print((seat.get("" + box + "D7")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "D7").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string52, 0, _jsp_string52.length);
    out.print((seat.get("" + box + "D8")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "D8").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string53, 0, _jsp_string53.length);
    out.print((seat.get("" + box + "D9")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "D9").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string54, 0, _jsp_string54.length);
    out.print((seat.get("" + box + "D10")));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    if (seat.get("" + box + "D10").equals("Y")) {
    out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string55, 0, _jsp_string55.length);
    
		}
	
    out.write(_jsp_string56, 0, _jsp_string56.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 4732978526484063000L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("selecttrain.jsp"), 4856925533088222066L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("include/resources.jsp"), 6804450726358218760L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string43;
  private final static char []_jsp_string51;
  private final static char []_jsp_string25;
  private final static char []_jsp_string5;
  private final static char []_jsp_string32;
  private final static char []_jsp_string40;
  private final static char []_jsp_string48;
  private final static char []_jsp_string21;
  private final static char []_jsp_string29;
  private final static char []_jsp_string37;
  private final static char []_jsp_string12;
  private final static char []_jsp_string11;
  private final static char []_jsp_string18;
  private final static char []_jsp_string26;
  private final static char []_jsp_string6;
  private final static char []_jsp_string54;
  private final static char []_jsp_string15;
  private final static char []_jsp_string2;
  private final static char []_jsp_string56;
  private final static char []_jsp_string52;
  private final static char []_jsp_string0;
  private final static char []_jsp_string33;
  private final static char []_jsp_string34;
  private final static char []_jsp_string41;
  private final static char []_jsp_string1;
  private final static char []_jsp_string45;
  private final static char []_jsp_string49;
  private final static char []_jsp_string3;
  private final static char []_jsp_string7;
  private final static char []_jsp_string22;
  private final static char []_jsp_string30;
  private final static char []_jsp_string38;
  private final static char []_jsp_string46;
  private final static char []_jsp_string19;
  private final static char []_jsp_string27;
  private final static char []_jsp_string35;
  private final static char []_jsp_string16;
  private final static char []_jsp_string8;
  private final static char []_jsp_string53;
  private final static char []_jsp_string42;
  private final static char []_jsp_string50;
  private final static char []_jsp_string23;
  private final static char []_jsp_string31;
  private final static char []_jsp_string39;
  private final static char []_jsp_string55;
  private final static char []_jsp_string47;
  private final static char []_jsp_string9;
  private final static char []_jsp_string44;
  private final static char []_jsp_string20;
  private final static char []_jsp_string28;
  private final static char []_jsp_string13;
  private final static char []_jsp_string36;
  private final static char []_jsp_string4;
  private final static char []_jsp_string17;
  private final static char []_jsp_string14;
  private final static char []_jsp_string24;
  private final static char []_jsp_string10;
  static {
    _jsp_string43 = "></td>\r\n										<td><input type=\"checkbox\" name=\"C9\"\r\n											value=\"".toCharArray();
    _jsp_string51 = "></td>\r\n										<td><input type=\"checkbox\" name=\"D7\"\r\n											value=\"".toCharArray();
    _jsp_string25 = "></td>\r\n									</tr>\r\n									<tr>\r\n										<td>B</td>\r\n										<td><input type=\"checkbox\" name=\"B1\"\r\n											value=\"".toCharArray();
    _jsp_string5 = ">\u7b2c2\u7bc0</option>\r\n							<option value=\"3\" ".toCharArray();
    _jsp_string32 = "></td>\r\n										<td><input type=\"checkbox\" name=\"B8\"\r\n											value=\"".toCharArray();
    _jsp_string40 = "></td>\r\n										<td><input type=\"checkbox\" name=\"C6\"\r\n											value=\"".toCharArray();
    _jsp_string48 = "></td>\r\n										<td><input type=\"checkbox\" name=\"D4\"\r\n											value=\"".toCharArray();
    _jsp_string21 = "></td>\r\n										<td><input type=\"checkbox\" name=\"A7\"\r\n											value=\"".toCharArray();
    _jsp_string29 = "></td>\r\n										<td><input type=\"checkbox\" name=\"B5\"\r\n											value=\"".toCharArray();
    _jsp_string37 = "></td>\r\n										<td><input type=\"checkbox\" name=\"C3\"\r\n											value=\"".toCharArray();
    _jsp_string12 = ">\u7b2c9\u7bc0</option>\r\n							<option value=\"10\" ".toCharArray();
    _jsp_string11 = ">\u7b2c8\u7bc0</option>\r\n							<option value=\"9\" ".toCharArray();
    _jsp_string18 = "></td>\r\n										<td><input type=\"checkbox\" name=\"A4\"\r\n											value=\"".toCharArray();
    _jsp_string26 = "></td>\r\n										<td><input type=\"checkbox\" name=\"B2\"\r\n											value=\"".toCharArray();
    _jsp_string6 = ">\u7b2c3\u7bc0</option>\r\n							<option value=\"4\" ".toCharArray();
    _jsp_string54 = "></td>\r\n										<td><input type=\"checkbox\" name=\"D10\"\r\n											value=\"".toCharArray();
    _jsp_string15 = " checked\r\n											".toCharArray();
    _jsp_string2 = "\" />\r\n		<div class=\"main\" id=\"main\">\r\n			<fieldset>\r\n				<legend>\u8eca\u6b21\u8eca\u4f4d\u7dad\u8b77</legend>\r\n				<div id=\"addtrain\">\r\n					<div class=\"carriage\">\r\n						<label for=\"trainCarri\">\u8eca\u7bb1:</label><select id=\"rainCarri\" id=\"box\"\r\n							name=\"box\">\r\n							<option value=\"1\" ".toCharArray();
    _jsp_string56 = "\r\n</body>\r\n</html>".toCharArray();
    _jsp_string52 = "></td>\r\n										<td><input type=\"checkbox\" name=\"D8\"\r\n											value=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta charset=\"UTF-8\">\r\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n<!-- \u8cc7\u6e90\u6a94 -->\r\n\r\n<title>\u53f0\u9435\u795e\u7968\u624b\u5f8c\u53f0</title>\r\n<link rel=\"shortcut icon\" href=\"image/logo.png\">\r\n<link rel=\"stylesheet\" href=\"css/screen.css\">\r\n<script\r\n	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n<script src=\"js/public.js\"></script>\r\n<link\r\n	href=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/hot-sneaks/jquery-ui.css\"\r\n	rel=\"stylesheet\">\r\n<script type=\"text/javascript\"\r\n	src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js\"></script>\r\n<script src=\"js/datepicker.js\"></script>\r\n<!-- \u522a\u9664\u6307\u4ee4\u7528\u5230 -->\r\n<script type=\"text/javascript\" src=\"/js/jquery.form.js\"></script>\r\n\r\n</head>\r\n<script type=\"text/javascript\">\r\n	function select() {\r\n\r\n		document.mform.action = \"selecttrain.jsp\";\r\n		document.mform.method = \"post\";\r\n		document.mform.submit();\r\n	}\r\n</script>\r\n<body>\r\n	".toCharArray();
    _jsp_string33 = "></td>\r\n										<td><input type=\"checkbox\" name=\"B9\"\r\n											value=\"".toCharArray();
    _jsp_string34 = "></td>\r\n										<td><input type=\"checkbox\" name=\"B10\"\r\n											value=\"".toCharArray();
    _jsp_string41 = "></td>\r\n										<td><input type=\"checkbox\" name=\"C7\"\r\n											value=\"".toCharArray();
    _jsp_string1 = "\r\n	<form action='updateTrain.jsp' method='post' name=\"mform\" id=\"mform\">\r\n		<input type=\"hidden\" id=\"id\" name=\"id\"\r\n			value=\"".toCharArray();
    _jsp_string45 = "></td>\r\n									</tr>\r\n									<tr>\r\n										<td>D</td>\r\n										<td><input type=\"checkbox\" name=\"D1\"\r\n											value=\"".toCharArray();
    _jsp_string49 = "></td>\r\n										<td><input type=\"checkbox\" name=\"D5\"\r\n											value=\"".toCharArray();
    _jsp_string3 = " SELECTED ".toCharArray();
    _jsp_string7 = ">\u7b2c4\u7bc0</option>\r\n							<option value=\"5\" ".toCharArray();
    _jsp_string22 = "></td>\r\n										<td><input type=\"checkbox\" name=\"A8\"\r\n											value=\"".toCharArray();
    _jsp_string30 = "></td>\r\n										<td><input type=\"checkbox\" name=\"B6\"\r\n											value=\"".toCharArray();
    _jsp_string38 = "></td>\r\n										<td><input type=\"checkbox\" name=\"C4\"\r\n											value=\"".toCharArray();
    _jsp_string46 = "></td>\r\n										<td><input type=\"checkbox\" name=\"D2\"\r\n											value=\"".toCharArray();
    _jsp_string19 = "></td>\r\n										<td><input type=\"checkbox\" name=\"A5\"\r\n											value=\"".toCharArray();
    _jsp_string27 = "></td>\r\n										<td><input type=\"checkbox\" name=\"B3\"\r\n											value=\"".toCharArray();
    _jsp_string35 = "></td>\r\n									</tr>\r\n									<tr>\r\n										<td>-</td>\r\n										<td>-</td>\r\n										<td>-</td>\r\n										<td>-</td>\r\n										<td>-</td>\r\n										<td>-</td>\r\n										<td>-</td>\r\n										<td>-</td>\r\n										<td>-</td>\r\n										<td>-</td>\r\n										<td>-</td>\r\n									</tr>\r\n									<tr>\r\n										<td>C</td>\r\n										<td><input type=\"checkbox\" name=\"C1\"\r\n											value=\"".toCharArray();
    _jsp_string16 = "></td>\r\n										<td><input type=\"checkbox\" name=\"A2\"\r\n											value=\"".toCharArray();
    _jsp_string8 = ">\u7b2c5\u7bc0</option>\r\n							<option value=\"6\" ".toCharArray();
    _jsp_string53 = "></td>\r\n										<td><input type=\"checkbox\" name=\"D9\"\r\n											value=\"".toCharArray();
    _jsp_string42 = "></td>\r\n										<td><input type=\"checkbox\" name=\"C8\"\r\n											value=\"".toCharArray();
    _jsp_string50 = "></td>\r\n										<td><input type=\"checkbox\" name=\"D6\"\r\n											value=\"".toCharArray();
    _jsp_string23 = "></td>\r\n										<td><input type=\"checkbox\" name=\"A9\"\r\n											value=\"".toCharArray();
    _jsp_string31 = "></td>\r\n										<td><input type=\"checkbox\" name=\"B7\"\r\n											value=\"".toCharArray();
    _jsp_string39 = "></td>\r\n										<td><input type=\"checkbox\" name=\"C5\"\r\n											value=\"".toCharArray();
    _jsp_string55 = "></td>\r\n									</tr>\r\n								</tbody>\r\n							</table>\r\n						</div>\r\n\r\n					</div>\r\n				</div>\r\n			</fieldset>\r\n		</div>\r\n	</form>\r\n	".toCharArray();
    _jsp_string47 = "></td>\r\n										<td><input type=\"checkbox\" name=\"D3\"\r\n											value=\"".toCharArray();
    _jsp_string9 = ">\u7b2c6\u7bc0</option>\r\n							<option value=\"7\" ".toCharArray();
    _jsp_string44 = "></td>\r\n										<td><input type=\"checkbox\" name=\"C10\"\r\n											value=\"".toCharArray();
    _jsp_string20 = "></td>\r\n										<td><input type=\"checkbox\" name=\"A6\"\r\n											value=\"".toCharArray();
    _jsp_string28 = "></td>\r\n										<td><input type=\"checkbox\" name=\"B4\"\r\n											value=\"".toCharArray();
    _jsp_string13 = ">\u7b2c10\u7bc0</option>\r\n						</select>\r\n						<button type=\"button\" onclick=\"javascript:select()\">\u67e5\u8a62</button>\r\n						<button type=\"summit\">\u66f4\u65b0</button>\r\n					</div>\r\n					<div class=\"trainbox\">\r\n						<div class=\"head\">\r\n							<div></div>\r\n							<div></div>\r\n						</div>\r\n\r\n						<div class=\"innerTrain\">\r\n							<table>\r\n								<thead>\r\n									<tr>\r\n										<th></th>\r\n										<th>1</th>\r\n										<th>2</th>\r\n										<th>3</th>\r\n										<th>4</th>\r\n										<th>5</th>\r\n										<th>6</th>\r\n										<th>7</th>\r\n										<th>8</th>\r\n										<th>9</th>\r\n										<th>10</th>\r\n									</tr>\r\n								</thead>\r\n								<tbody>\r\n									<tr>\r\n										<td>A</td>\r\n										<td><input type=\"checkbox\" name=\"A1\"\r\n											value=\"".toCharArray();
    _jsp_string36 = "></td>\r\n										<td><input type=\"checkbox\" name=\"C2\"\r\n											value=\"".toCharArray();
    _jsp_string4 = ">\u7b2c1\u7bc0</option>\r\n							<option value=\"2\" ".toCharArray();
    _jsp_string17 = "></td>\r\n										<td><input type=\"checkbox\" name=\"A3\"\r\n											value=\"".toCharArray();
    _jsp_string14 = "\"\r\n											".toCharArray();
    _jsp_string24 = "></td>\r\n										<td><input type=\"checkbox\" name=\"A10\"\r\n											value=\"".toCharArray();
    _jsp_string10 = ">\u7b2c7\u7bc0</option>\r\n							<option value=\"8\" ".toCharArray();
  }
}
