/*
 * JSP generated by Resin Professional 4.0.53 (built Fri, 16 Jun 2017 02:25:02 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import tw.com.common.*;
import java.util.*;

public class _updatetrain__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
		Map<String, String> seat = new HashMap<String, String>();

		//\u89e3\u6c7a\u7de8\u78bc\u554f\u984c
		request.setCharacterEncoding("UTF-8");
		//\u63a5\u6536\u53c3\u6578
		String Id = (String) request.getParameter("id");
		String box = (String) request.getParameter("box");
		String A1 = (String) request.getParameter("A1");
		TrainData trainDate = new TrainData();
		ArrayList<Station_trainItem> lists = trainDate.SelectTrainSeat(Id);
		Map<String, String> seat2 = lists.get(0).getSeat();
		if (A1 != null) {
			A1 = "Y";
		} else {
			A1 = "N";
		}
		String A2 = (String) request.getParameter("A2");
		if (A2 != null) {
			A2 = "Y";
		} else {
			A2 = "N";
		}
		String A3 = (String) request.getParameter("A3");
		if (A3 != null) {
			A3 = "Y";
		} else {
			A3 = "N";
		}
		String A4 = (String) request.getParameter("A4");
		if (A4 != null) {
			A4 = "Y";
		} else {
			A4 = "N";
		}
		String A5 = (String) request.getParameter("A5");
		if (A5 != null) {
			A5 = "Y";
		} else {
			A5 = "N";
		}
		String A6 = (String) request.getParameter("A6");
		if (A6 != null) {
			A6 = "Y";
		} else {
			A6 = "N";
		}
		String A7 = (String) request.getParameter("A7");
		if (A7 != null) {
			A7 = "Y";
		} else {
			A7 = "N";
		}
		String A8 = (String) request.getParameter("A8");
		if (A8 != null) {
			A8 = "Y";
		} else {
			A8 = "N";
		}
		String A9 = (String) request.getParameter("A9");
		if (A9 != null) {
			A9 = "Y";
		} else {
			A9 = "N";
		}
		String A10 = (String) request.getParameter("A10");
		if (A10 != null) {
			A10 = "Y";
		} else {
			A10 = "N";
		}

		String B1 = (String) request.getParameter("B1");
		if (B1 != null) {
			B1 = "Y";
		} else {
			B1 = "N";
		}
		String B2 = (String) request.getParameter("B2");
		if (B2 != null) {
			B2 = "Y";
		} else {
			B2 = "N";
		}
		String B3 = (String) request.getParameter("B3");
		if (B3 != null) {
			B3 = "Y";
		} else {
			B3 = "N";
		}
		String B4 = (String) request.getParameter("B4");
		if (B4 != null) {
			B4 = "Y";
		} else {
			B4 = "N";
		}
		String B5 = (String) request.getParameter("B5");
		if (B5 != null) {
			B5 = "Y";
		} else {
			B5 = "N";
		}
		String B6 = (String) request.getParameter("B6");
		if (B6 != null) {
			B6 = "Y";
		} else {
			B6 = "N";
		}
		String B7 = (String) request.getParameter("B7");
		if (B7 != null) {
			B7 = "Y";
		} else {
			B7 = "N";
		}
		String B8 = (String) request.getParameter("B8");
		if (B8 != null) {
			B8 = "Y";
		} else {
			B8 = "N";
		}
		String B9 = (String) request.getParameter("B9");
		if (B9 != null) {
			B9 = "Y";
		} else {
			B9 = "N";
		}
		String B10 = (String) request.getParameter("B10");
		if (B10 != null) {
			B10 = "Y";
		} else {
			B10 = "N";
		}

		String C1 = (String) request.getParameter("C1");
		if (C1 != null) {
			C1 = "Y";
		} else {
			C1 = "N";
		}
		String C2 = (String) request.getParameter("C2");
		if (C2 != null) {
			C2 = "Y";
		} else {
			C2 = "N";
		}
		String C3 = (String) request.getParameter("C3");
		if (C3 != null) {
			C3 = "Y";
		} else {
			C3 = "N";
		}
		String C4 = (String) request.getParameter("C4");
		if (C4 != null) {
			C4 = "Y";
		} else {
			C4 = "N";
		}
		String C5 = (String) request.getParameter("C5");
		if (C5 != null) {
			C5 = "Y";
		} else {
			C5 = "N";
		}
		String C6 = (String) request.getParameter("C6");
		if (C6 != null) {
			C6 = "Y";
		} else {
			C6 = "N";
		}
		String C7 = (String) request.getParameter("C7");
		if (C7 != null) {
			C7 = "Y";
		} else {
			C7 = "N";
		}
		String C8 = (String) request.getParameter("C8");
		if (C8 != null) {
			C8 = "Y";
		} else {
			C8 = "N";
		}
		String C9 = (String) request.getParameter("C9");
		if (C9 != null) {
			C9 = "Y";
		} else {
			C9 = "N";
		}
		String C10 = (String) request.getParameter("C10");
		if (C10 != null) {
			C10 = "Y";
		} else {
			C10 = "N";
		}

		String D1 = (String) request.getParameter("D1");
		if (D1 != null) {
			D1 = "Y";
		} else {
			D1 = "N";
		}
		String D2 = (String) request.getParameter("D2");
		if (D2 != null) {
			D2 = "Y";
		} else {
			D2 = "N";
		}
		String D3 = (String) request.getParameter("D3");
		if (D3 != null) {
			D3 = "Y";
		} else {
			D3 = "N";
		}
		String D4 = (String) request.getParameter("D4");
		if (D4 != null) {
			D4 = "Y";
		} else {
			D4 = "N";
		}
		String D5 = (String) request.getParameter("D5");
		if (D5 != null) {
			D5 = "Y";
		} else {
			D5 = "N";
		}
		String D6 = (String) request.getParameter("D6");
		if (D6 != null) {
			D6 = "Y";
		} else {
			D6 = "N";
		}
		String D7 = (String) request.getParameter("D7");
		if (D7 != null) {
			D7 = "Y";
		} else {
			D7 = "N";
		}
		String D8 = (String) request.getParameter("D8");
		if (D8 != null) {
			D8 = "Y";
		} else {
			D8 = "N";
		}
		String D9 = (String) request.getParameter("D9");
		if (D9 != null) {
			D9 = "Y";
		} else {
			D9 = "N";
		}
		String D10 = (String) request.getParameter("D10");
		if (D10 != null) {
			D10 = "Y";
		} else {
			D10 = "N";
		}
		if (box.equals("1")) {
			// \u7b2c\u4e00\u7bc0\u8eca\u5ec2
			seat.put("1A1", A1);
			seat.put("1A2", A2);
			seat.put("1A3", A3);
			seat.put("1A4", A4);
			seat.put("1A5", A5);
			seat.put("1A6", A6);
			seat.put("1A7", A7);
			seat.put("1A8", A8);
			seat.put("1A9", A9);
			seat.put("1A10", A10);

			seat.put("1B1", B1);
			seat.put("1B2", B2);
			seat.put("1B3", B3);
			seat.put("1B4", B4);
			seat.put("1B5", B5);
			seat.put("1B6", B6);
			seat.put("1B7", B7);
			seat.put("1B8", B8);
			seat.put("1B9", B9);
			seat.put("1B10", B10);

			seat.put("1C1", C1);
			seat.put("1C2", C2);
			seat.put("1C3", C3);
			seat.put("1C4", C4);
			seat.put("1C5", C5);
			seat.put("1C6", C6);
			seat.put("1C7", C7);
			seat.put("1C8", C8);
			seat.put("1C9", C9);
			seat.put("1C10", C10);

			seat.put("1D1", D1);
			seat.put("1D2", D2);
			seat.put("1D3", D3);
			seat.put("1D4", D4);
			seat.put("1D5", D5);
			seat.put("1D6", D6);
			seat.put("1D7", D7);
			seat.put("1D8", D8);
			seat.put("1D9", D9);
			seat.put("1D10", D10);
			// \u7b2c\u4e8c\u7bc0\u8eca\u5ec2
			seat.put("2A1", seat2.get("2A1"));
			seat.put("2A2", seat2.get("2A2"));
			seat.put("2A3", seat2.get("2A3"));
			seat.put("2A4", seat2.get("2A4"));
			seat.put("2A5", seat2.get("2A5"));
			seat.put("2A6", seat2.get("2A6"));
			seat.put("2A7", seat2.get("2A7"));
			seat.put("2A8", seat2.get("2A8"));
			seat.put("2A9", seat2.get("2A9"));
			seat.put("2A10", seat2.get("2A10"));

			seat.put("2B1", seat2.get("2B1"));
			seat.put("2B2", seat2.get("2B2"));
			seat.put("2B3", seat2.get("2B3"));
			seat.put("2B4", seat2.get("2B4"));
			seat.put("2B5", seat2.get("2B5"));
			seat.put("2B6", seat2.get("2B6"));
			seat.put("2B7", seat2.get("2B7"));
			seat.put("2B8", seat2.get("2B8"));
			seat.put("2B9", seat2.get("2B9"));
			seat.put("2B10", seat2.get("2B10"));

			seat.put("2C1", seat2.get("2C1"));
			seat.put("2C2", seat2.get("2C2"));
			seat.put("2C3", seat2.get("2C3"));
			seat.put("2C4", seat2.get("2C4"));
			seat.put("2C5", seat2.get("2C5"));
			seat.put("2C6", seat2.get("2C6"));
			seat.put("2C7", seat2.get("2C7"));
			seat.put("2C8", seat2.get("2C8"));
			seat.put("2C9", seat2.get("2C9"));
			seat.put("2C10", seat2.get("2C10"));

			seat.put("2D1", seat2.get("2D1"));
			seat.put("2D2", seat2.get("2D2"));
			seat.put("2D3", seat2.get("2D3"));
			seat.put("2D4", seat2.get("2D4"));
			seat.put("2D5", seat2.get("2D5"));
			seat.put("2D6", seat2.get("2D6"));
			seat.put("2D7", seat2.get("2D7"));
			seat.put("2D8", seat2.get("2D8"));
			seat.put("2D9", seat2.get("2D9"));
			seat.put("2D10", seat2.get("2D10"));

		} else if (box.equals("2")) {
			// \u7b2c\u4e8c\u7bc0\u8eca\u5ec2
			seat.put("2A1", A1);
			seat.put("2A2", A2);
			seat.put("2A3", A3);
			seat.put("2A4", A4);
			seat.put("2A5", A5);
			seat.put("2A6", A6);
			seat.put("2A7", A7);
			seat.put("2A8", A8);
			seat.put("2A9", A9);
			seat.put("2A10", A10);

			seat.put("2B1", B1);
			seat.put("2B2", B2);
			seat.put("2B3", B3);
			seat.put("2B4", B4);
			seat.put("2B5", B5);
			seat.put("2B6", B6);
			seat.put("2B7", B7);
			seat.put("2B8", B8);
			seat.put("2B9", B9);
			seat.put("2B10", B10);

			seat.put("2C1", C1);
			seat.put("2C2", C2);
			seat.put("2C3", C3);
			seat.put("2C4", C4);
			seat.put("2C5", C5);
			seat.put("2C6", C6);
			seat.put("2C7", C7);
			seat.put("2C8", C8);
			seat.put("2C9", C9);
			seat.put("2C10", C10);

			seat.put("2D1", D1);
			seat.put("2D2", D2);
			seat.put("2D3", D3);
			seat.put("2D4", D4);
			seat.put("2D5", D5);
			seat.put("2D6", D6);
			seat.put("2D7", D7);
			seat.put("2D8", D8);
			seat.put("2D9", D9);
			seat.put("2D10", D10);
			// \u7b2c\u4e00\u7bc0\u8eca\u5ec2
			seat.put("1A1", seat2.get("1A1"));
			seat.put("1A2", seat2.get("1A1"));
			seat.put("1A3", seat2.get("1A3"));
			seat.put("1A4", seat2.get("1A4"));
			seat.put("1A5", seat2.get("1A5"));
			seat.put("1A6", seat2.get("1A6"));
			seat.put("1A7", seat2.get("1A7"));
			seat.put("1A8", seat2.get("1A8"));
			seat.put("1A9", seat2.get("1A9"));
			seat.put("1A10", seat2.get("1A10"));

			seat.put("1B1", seat2.get("1B1"));
			seat.put("1B2", seat2.get("1B2"));
			seat.put("1B3", seat2.get("1B3"));
			seat.put("1B4", seat2.get("1B4"));
			seat.put("1B5", seat2.get("1B5"));
			seat.put("1B6", seat2.get("1B6"));
			seat.put("1B7", seat2.get("1B7"));
			seat.put("1B8", seat2.get("1B8"));
			seat.put("1B9", seat2.get("1B9"));
			seat.put("1B10", seat2.get("1B10"));

			seat.put("1C1", seat2.get("1C1"));
			seat.put("1C2", seat2.get("1C2"));
			seat.put("1C3", seat2.get("1C3"));
			seat.put("1C4", seat2.get("1C4"));
			seat.put("1C5", seat2.get("1C5"));
			seat.put("1C6", seat2.get("1C6"));
			seat.put("1C7", seat2.get("1C7"));
			seat.put("1C8", seat2.get("1C8"));
			seat.put("1C9", seat2.get("1C9"));
			seat.put("1C10", seat2.get("1C10"));

			seat.put("1D1", seat2.get("1D1"));
			seat.put("1D2", seat2.get("1D2"));
			seat.put("1D3", seat2.get("1D3"));
			seat.put("1D4", seat2.get("1D4"));
			seat.put("1D5", seat2.get("1D5"));
			seat.put("1D6", seat2.get("1D6"));
			seat.put("1D7", seat2.get("1D7"));
			seat.put("1D8", seat2.get("1D8"));
			seat.put("1D9", seat2.get("1D9"));
			seat.put("1D10", seat2.get("1D10"));

		}
		TrainData trainData = new TrainData();
		boolean check = trainData.UpdateTrains(Id, seat);
		if (check) {
			System.out.println("\u66f4\u65b0\u6210\u529f");
	
    out.write(_jsp_string1, 0, _jsp_string1.length);
    
		} else {
			System.out.println("\u66f4\u65b0\u5931\u6557");
	
    out.write(_jsp_string2, 0, _jsp_string2.length);
    
		}
	
    out.write(_jsp_string3, 0, _jsp_string3.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 4732978526484063000L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("updateTrain.jsp"), 8115271500396019473L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("include/resources.jsp"), 6804450726358218760L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  private final static char []_jsp_string3;
  private final static char []_jsp_string1;
  static {
    _jsp_string2 = "\r\n	<script>\r\n		alert(\"\u66f4\u65b0\u5931\u6557!\");\r\n		window.location.href = \"train.jsp\";\r\n	</script>\r\n	".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=BIG5\">\r\n<!-- \u8cc7\u6e90\u6a94 -->\r\n\r\n<title>\u53f0\u9435\u795e\u7968\u624b\u5f8c\u53f0</title>\r\n<link rel=\"shortcut icon\" href=\"image/logo.png\">\r\n<link rel=\"stylesheet\" href=\"css/screen.css\">\r\n<script\r\n	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n<script src=\"js/public.js\"></script>\r\n<link\r\n	href=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/hot-sneaks/jquery-ui.css\"\r\n	rel=\"stylesheet\">\r\n<script type=\"text/javascript\"\r\n	src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js\"></script>\r\n<script src=\"js/datepicker.js\"></script>\r\n<!-- \u522a\u9664\u6307\u4ee4\u7528\u5230 -->\r\n<script type=\"text/javascript\" src=\"/js/jquery.form.js\"></script>\r\n\r\n</head>\r\n<body>\r\n	".toCharArray();
    _jsp_string3 = "\r\n\r\n</body>\r\n</html>".toCharArray();
    _jsp_string1 = "\r\n	<script>\r\n		alert(\"\u66f4\u65b0\u6210\u529f!\");\r\n		window.location.href = \"train.jsp\";\r\n	</script>\r\n	".toCharArray();
  }
}
